[package]
name = "braces"
version = "0.1.0"
authors = ["certainty <david.krentzlin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="braces"
path="src/lib.rs"

[features]
debug_vm = []

[dependencies]
# utils
log="0.4"
env_logger = "0.8"
pretty_env_logger = "0.4"
thiserror = "1.0"
anyhow = "1.0"

# parser
pest = "2.1"
pest_derive = "2.1"

# compiler / interpreter
clap-v3 = "3.0.0-beta.1"
rustyline = "8.0.0"
hashbrown = "0.11"
fasthash = "0.4.0"

[dev-dependencies]
matches = "0.1"
