[package]
name = "braces"
version = "0.1.0"
authors = ["certainty <david.krentzlin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="braces"
path="src/lib.rs"

[dependencies]
clap-v3 = "3.0.0-beta.1"
env_logger = "0.8"
pretty_env_logger = "0.4"
